name: Main workflow

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  main:
    name: Lint and unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Trigger platform-pr-features-talent-profile job
        uses: toptal/jenkins-job-trigger-action@0.0.2
        with:
          jenkins_url: 'https://jenkins.net/'
          jenkins_user: 'yo'
          jenkins_token: 'token'
          job_name: 'jobname'
          job_params: '{}'
          job_timeout: '3600'

