name: Master

on:
  issue_comment:
    types:
      - created
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  master:
    name: Master
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Print job url
        run: echo ${{ fromJson(job.html_url) }}

      - name: Print job name
        run: echo `${{ fronJson(job.name) }}`
